Repository DevMed22/Revive_My_Memory, pull requests merged in 2023-03, with the labels that each got.

#65 Build Tasks API
  backend/api/serializers.py
  backend/api/urls.py
  backend/api/views.py
  backend/posts/migrations/0002_alter_post_thumb_alter_post_updated_at.py
  backend/posts/models.py
  backend/requirmenst.txt
  backend/root/settings.py
  backend/tasks/__init__.py
  backend/tasks/admin.py
  backend/tasks/apps.py
  backend/tasks/migrations/0001_initial.py
  backend/tasks/migrations/__init__.py
  backend/tasks/models.py
  backend/tasks/tests.py
  backend/tasks/views.py
Labels: enhancement, Web

#66 Build Token generation API
  backend/api/serializers.py
  backend/api/urls.py
  backend/api/views.py
  backend/requirements.txt
  backend/requirmenst.txt
  backend/root/settings.py
Labels: enhancement, Web

#60 MLOps RoadMap
  models/images/MLOps-roadmap.PNG
Labels: documentation, AI, DevOps

#63 Documentation
  Documentation/Untitled Diagram.drawio
  Documentation/class Diagram.drawio
  Documentation/context Diagram.drawio (1).drawio
  Documentation/context Diagram.drawio (1).pdf
  Documentation/digital ocean.docx
  Documentation/domain.docx
  Documentation/python anyway hosting.docx
  Documentation/sequence Diagram.drawio (1).pdf
  Documentation/sequence Diagram.drawio.pdf
  Documentation/~$gital ocean.docx
  Documentation/~$thon anyway hosting.docx
Labels: documentation, Web, DevOps

#89 Add endpoints for users registration
  Documentation/Agora Steps.docx
  backend/api/serializers.py
  backend/api/urls.py
  backend/api/views.py
  backend/media/Screenshot_2023-03-02_132708.png
  backend/root/settings.py
  backend/root/urls.py
Labels: enhancement, Web

#91 Add steps for AI with Django
  Documentation/BACKEND/AI with Django.docx
  Documentation/BACKEND/Agora Steps.docx
  Documentation/DEVOPS/digital ocean.docx
  Documentation/DEVOPS/domain.docx
  Documentation/DEVOPS/python anyway hosting.docx
  Documentation/DEVOPS/~$gital ocean.docx
  Documentation/DEVOPS/~$thon anyway hosting.docx
  Documentation/DIAGRAMS/Revive my memory (1).png
  Documentation/DIAGRAMS/Untitled Diagram.drawio
  Documentation/DIAGRAMS/Use Case.pdf
  Documentation/DIAGRAMS/activity.drawio.pdf
  Documentation/DIAGRAMS/class Diagram.drawio
  Documentation/DIAGRAMS/context Diagram.drawio (1).drawio
  Documentation/DIAGRAMS/context Diagram.drawio (1).pdf
  Documentation/DIAGRAMS/sequence Diagram.drawio.pdf
  backend/requirements.txt
Labels: documentation, AI, Web

#92 word file describe react structure
  Documentation/FRONTEND/react structure.docx
Labels: documentation

#94 Token Auth
  backend/api/views.py
Labels: bug
